name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # یا شاخه‌ای که Deploy می‌کنی

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Authenticate Wrangler
        run: wrangler login

      - name: Publish Pages
        run: wrangler pages publish ./ --project-name="cafe-menu" --branch=main
